<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link href="/css/style.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<div class="back">
    <div class="div-center">
        <div class="content">
            <div class="container-fluid h-100">
                <div class="row h-25">
                    <div class="col-md-12">
                        <h1 class="text-center">
                            Converter Archive WEBP
                        </h1>
                    </div>
                </div>
                <div class="h-75">
                    <div class="d-flex aligns-items-center justify-content-center mx-auto">
                        <form action="/convert-to-zip-webp-download" method="post" enctype="multipart/form-data">
                            <input class="form-control form-control-lg" type="file" id="file" name="file">
                            <input class="btn btn-success btn-block btn-lg w-100 my-3" type="submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>