<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link href="/css/style.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<div class="back">
    <div class="div-center">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="text-center">
                            Converter
                        </h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 p-4">
                        <h3 class="text-center">
                            WEBP
                        </h3>
                        <a href="/zip-file-converter" class="btn btn-success btn-block btn-lg w-100 my-3" role="button">Convert
                            Archive</a>
                        <a href="/single-file-converter" class="btn btn-success btn-block btn-lg w-100 my-3"
                           role="button">Convert File</a>
                    </div>
                    <div class="col-md-6 p-4">
                        <h3 class="text-center">
                            AVIF
                        </h3>
                        <a href="/" class="btn btn-success btn-block btn-lg w-100 my-3" role="button">Convert
                            Archive</a>
                        <a href="/single-file-converter" class="btn btn-success btn-block btn-lg w-100 my-3"
                           role="button">Convert File</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>